config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  if Rails.env.development?
    mount GovukPublishingComponents::Engine, at: "/component-guide"
  end

  resources :quizzes do
    resources :questions
  end

  scope "/take-quiz/:quiz_id", as: "take_quiz" do
    get "/guest_prompt", to: "take_quiz#guest_prompt", as: "guest_prompt"
    post "/guest_username", to: "take_quiz#set_guest_username", as: "set_guest_username"
    get "/results", to: "take_quiz#results", as: "results"
    get "/:question_id", to: "take_quiz#question", as: "question"
    post "/:question_id/submit", to: "take_quiz#submit", as: "submit"
  end

  root "quizzes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz

  enum :correct_option, {
    option_a: "option_a",
    option_b: "option_b",
    option_c: "option_c",
    option_d: "option_d",
  }

  validates :content, :option_a, :option_b, :option_c, :option_d, presence: { message: "Field can't be blank" }
  validates :correct_option, inclusion: { in: %w[option_a option_b option_c option_d], message: "Please select one of the options" }

  def correct_answer
    raise "No answer defined" if correct_option.blank?

    public_send(correct_option.to_sym)
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :questions, -> { order(:id) }, dependent: :destroy

  validates :title, presence: { message: "Please enter a title for your quiz" }
  validates :description, presence: { message: "Please provide a description for your quiz" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  has_many :quizzes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_quiz
  before_action :find_question, only: %i[edit update destroy]

  def new
    @question = @quiz.questions.build
  end

  def create
    @question = @quiz.questions.build(question_params)
    if @question.save
      redirect_to quiz_path(@quiz)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to quiz_path(@quiz)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy!
    redirect_to quiz_path(@quiz)
  end

private

  def find_quiz
    @quiz = current_user.quizzes.find(params[:quiz_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "You are not authorised to modify this quiz."
    redirect_to quiz_path(params[:quiz_id])
  end

  def find_question
    @question = @quiz.questions.find(params[:id])
  end

  def question_params
    params.expect(question: %i[content option_a option_b option_c option_d correct_option])
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_quiz, only: %i[show edit update destroy]

  def index
    @quizzes = Quiz.all
  end

  def show; end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = current_user.quizzes.build(quiz_params)
    if @quiz.save
      redirect_to @quiz, notice: "Quiz was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @quiz.update(quiz_params)
      redirect_to @quiz, notice: "Quiz was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quiz.destroy!
    redirect_to quizzes_path, notice: "Quiz was successfully deleted."
  end

private

  def quiz_params
    params.expect(quiz: %i[title description])
  end

  def find_quiz
    @quiz = if %w[edit update destroy].include?(action_name)
              current_user.quizzes.find(params[:id])
            else
              Quiz.find(params[:id])
            end
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "You are not authorised to perform that action."
    redirect_to quiz_path(params[:id])
  end
end

app/controllers/take_quiz_controller.rb
class TakeQuizController < ApplicationController
  before_action :set_quiz
  before_action :ensure_guest_or_signed_in, except: %i[guest_prompt set_guest_username]

  def guest_prompt; end

  def set_guest_username
    session[:guest_username] = params[:guest_username]
    redirect_to quiz_path(@quiz)
  end

  def question
    @question = @quiz.questions.find(params[:question_id])
    question_ids = @quiz.questions.order(:id).ids
    @question_index = question_ids.index(@question.id)
  end

  def submit
    current_question = @quiz.questions.find(params[:question_id])
    user_answer = params[:answer]
    session[:quiz_answers] ||= {}
    session[:quiz_answers][@quiz.id.to_s] ||= {}
    session[:quiz_answers][@quiz.id.to_s][current_question.id.to_s] = user_answer

    next_question = @quiz.questions.where("id > ?", current_question.id).first

    if next_question
      redirect_to take_quiz_question_path(@quiz.id, next_question.id)
    else
      redirect_to take_quiz_results_path(@quiz.id)
    end
  end

  def results
    user_answers = session[:quiz_answers]&.[](@quiz.id.to_s) || {}
    @score = @quiz.questions.sum do |q|
      user_answer = user_answers[q.id.to_s]
      next 0 unless user_answer

      user_answer == q.correct_option ? 1 : 0
    end

    @guest_username = session[:guest_username] unless user_signed_in?

    session.delete(:guest_username)
  end

private

  def set_quiz
    @quiz = Quiz.find(params[:quiz_id])
  end

  def ensure_guest_or_signed_in
    unless user_signed_in? || session[:guest_username].present?
      redirect_to take_quiz_guest_prompt_path(@quiz.id), alert: "Please enter your guest username to continue."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<%# app/views/layouts/application.html.erb %>
<% if user_signed_in? %>
  <% nav_items = [
       { text: "Welcome, #{current_user.username}", href: nil },
       { text: "Sign Out", href: destroy_user_session_path, data: { method: "delete", rel: "nofollow" } }
     ] %>
<% else %>
  <% nav_items = [
       { text: "Sign In", href: new_user_session_path }
     ] %>
<% end %>

<%= render "govuk_publishing_components/components/layout_for_admin", {
  environment: "development",
  product_name: "Quiz",
  browser_title: yield(:page_title)
} do %>
  <%= render "govuk_publishing_components/components/layout_header", {
        environment: "development",
        navigation_items: nav_items
      } %>
  
  <div class="govuk-width-container">
    <% if content_for?(:back_link) %>
      <%= render "govuk_publishing_components/components/back_link", href: yield(:back_link) %>
    <% end %>
    <main class="govuk-main-wrapper" id="main-content">
      <% if content_for?(:page_title) %>
        <h1 class="govuk-heading-xl"><%= yield(:page_title) %></h1>
      <% end %>    
    <% if flash[:alert].present? %>
      <%= render "govuk_publishing_components/components/error_alert", { message: flash[:alert] } %>
    <% end %>
      <%= yield %>
    </main>
  </div>
  <%= render "govuk_publishing_components/components/layout_footer", {} %>
<% end %>

app/views/questions/_form.html.erb
<% if @question.errors.any? %>
  <%= render "govuk_publishing_components/components/error_alert", {
    message: "There were errors with your submission. Please fix them below."
  } %>
<% end %>

<%= form_with(model: [@quiz, @question], local: true) do |f| %>
  <%= render "govuk_publishing_components/components/input", {
    label: { text: "Question" },
    name: "question[content]",
    value: @question.content,
    id: "question_content",
    error_items: @question.errors[:content].map { |message| { text: message } }
  } %>

  <%= render "govuk_publishing_components/components/input", {
    label: { text: "Option A" },
    name: "question[option_a]",
    value: @question.option_a,
    id: "question_option_a",
    error_items: @question.errors[:option_a].map { |message| { text: message } }
  } %>

  <%= render "govuk_publishing_components/components/input", {
    label: { text: "Option B" },
    name: "question[option_b]",
    value: @question.option_b,
    id: "question_option_b",
    error_items: @question.errors[:option_b].map { |message| { text: message } }
    } %>

  <%= render "govuk_publishing_components/components/input", {
    label: { text: "Option C" },
    name: "question[option_c]",
    value: @question.option_c,
    id: "question_option_c",
    error_items: @question.errors[:option_c].map { |message| { text: message } }
    } %>

  <%= render "govuk_publishing_components/components/input", {
    label: { text: "Option D" },
    name: "question[option_d]",
    value: @question.option_d,
    id: "question_option_d",
    error_items: @question.errors[:option_d].map { |message| { text: message } }
    } %>

  <%= render "govuk_publishing_components/components/radio", {
    heading: "Select the correct option",
    name: "question[correct_option]",
    items: [
      { value: "option_a", text: "Option A" },
      { value: "option_b", text: "Option B" },
      { value: "option_c", text: "Option C" },
      { value: "option_d", text: "Option D" }
    ],
    error_items: @question.errors[:correct_option].map { |message| { text: message } }
    } %>

  <%= f.submit "Save", class: "govuk-button" %>
<% end %>

app/views/questions/edit.html.erb
<% content_for :page_title, "Edit Question" %>
<% content_for :back_link, quiz_path(@quiz) %>

<%= render "form" %>

app/views/questions/new.html.erb
<% content_for :page_title, "Add a New Question" %>
<% content_for :back_link, quiz_path(@quiz) %>

<%= render "form" %>

app/views/quizzes/_form.html.erb
<% if @quiz.errors.any? %>
  <%= render "govuk_publishing_components/components/error_alert", {
    message: "There were errors with your submission. Please fix them below."
  } %>
<% end %>

<%= form_with model: @quiz, local: true do |form| %>
    <%= render "govuk_publishing_components/components/input", {
          label: { text: "Title" },
          name: "quiz[title]",
          value: @quiz.title,
          id: "quiz_title",
          error_items: @quiz.errors[:title].map { |message| { text: message } }
        } %>
        
    <%= render "govuk_publishing_components/components/input", {
          label: { text: "Description" },
          name: "quiz[description]",
          value: @quiz.description,
          id: "quiz_description",
          error_items: @quiz.errors[:description].map { |message| { text: message } }
        } %>
        
    <div class="govuk-form-group">
      <%= render "govuk_publishing_components/components/button", { text: button_text, type: "submit" } %>
    </div>
  <% end %>
  

app/views/quizzes/edit.html.erb
<% content_for :page_title, "Edit a Quiz" %>
<% content_for :back_link, quiz_path(@quiz) %>

<%= render "form", button_text: "Update Quiz" %>

app/views/quizzes/index.html.erb
<% content_for :page_title, "Quizzes Dashboard" %>

<p class="govuk-body">
  Manage and review your quizzes below. Create new quizzes or modify existing ones to keep your content up-to-date.
</p>

<%= render "govuk_publishing_components/components/button", text: "Create New Quiz", href: new_quiz_path %>

<h2 class="govuk-heading-m govuk-!-margin-top-3">Existing Quizzes</h2>
<%= render "govuk_publishing_components/components/cards", {
  columns: 3,
  items: @quizzes.map do |quiz|
    {
      link: {
        text: quiz.title,
        path: quiz_path(quiz)
      },
      description: quiz.description
    }
  end
} %>

app/views/quizzes/new.html.erb
<% content_for :page_title, "Create a New Quiz" %>
<% content_for :back_link, quizzes_path %>

<%= render "form", button_text: "Create Quiz" %>

app/views/quizzes/show.html.erb
<% content_for :page_title, @quiz.title %>
<% content_for :back_link, quizzes_path %>

<p class="govuk-body"><%= @quiz.description %></p>

<% if @quiz.questions.any? %>
  <div class="govuk-button-group">
    <%= render "govuk_publishing_components/components/button", {
          text: "Start now",
          href: take_quiz_question_path(@quiz.id, @quiz.questions.first.id),
          start: true
        } %>
  </div>
<% end %>

<h2 class="govuk-heading-m">Questions</h2>
<ul class="govuk-list">
  <% @quiz.questions.each do |question| %>
    <li class="govuk-body">
      <%= question.content %> (Answer: <%= question.correct_answer %>)
      <div class="govuk-button-group">
        <%= render "govuk_publishing_components/components/button", text: "Edit", href: edit_quiz_question_path(@quiz, question) %>
        <%= link_to "Delete", quiz_question_path(@quiz, question), method: :delete, data: { confirm: "Are you sure you want to delete this question?" }, class: "govuk-button govuk-button--warning" %>
      </div>
    </li>
  <% end %>
</ul>

<div class="govuk-button-group">
  <%= render "govuk_publishing_components/components/button", text: "Add Question", href: new_quiz_question_path(@quiz) %>
</div>

<div class="govuk-button-group">
  <%= render "govuk_publishing_components/components/button", text: "Edit Quiz", href: edit_quiz_path(@quiz) %>
  <%= link_to "Delete Quiz", quiz_path(@quiz), method: :delete, data: { confirm: "Are you sure you want to delete this quiz?" }, class: "govuk-button govuk-button--warning" %>
</div>

app/views/quizzes/take.html.erb
<% content_for :page_title, "#{@quiz.title}" %>
<% content_for :back_link, quiz_path(@quiz) %>

<p class="govuk-body">Question <%= @question_index + 1 %> of <%= @quiz.questions.count %>:</p>

<div class="govuk-!-margin-bottom-5">
    <p class="govuk-body"><%= @question.content %></p>
</div>

<%= form_with url: submit_quiz_path(@quiz), method: :post, local: true do |form| %>
<%= render "govuk_publishing_components/components/input", {
      label: { text: "Your Answer" },
      name: "answer"
    } %>
<%= hidden_field_tag "question_id", @question.id %>
<%= render "govuk_publishing_components/components/button", { text: "Submit Answer" } %>
<% end %>

app/views/take_quiz/guest_prompt.html.erb
<% content_for :page_title, "Guest Access" %>
<% content_for :back_link, quiz_path(@quiz) %>

<%= form_with url: take_quiz_set_guest_username_path(@quiz.id), local: true do |f| %>
  <%= render "govuk_publishing_components/components/input", {
        label: { text: "Guest Username" },
        name: "guest_username",
        required: true
      } %>
  <%= render "govuk_publishing_components/components/button", { text: "Continue", type: "submit" } %>
<% end %>

app/views/take_quiz/question.html.erb
<% content_for :page_title, "#{@quiz.title}" %>
<% content_for :back_link, quiz_path(@quiz) %>

<p class="govuk-body">Question <%= @question_index + 1 %> of <%= @quiz.questions.count %>:</p>

<div class="govuk-!-margin-bottom-5">
  <p class="govuk-body"><%= @question.content %></p>
</div>

<%= form_with url: take_quiz_submit_path(@quiz.id, @question.id), method: :post, local: true do |form| %>
  <%= render "govuk_publishing_components/components/radio", {
        heading: "Choose your answer",
        name: "answer",
        items: [
          { value: "option_a", text: @question.option_a },
          { value: "option_b", text: @question.option_b },
          { value: "option_c", text: @question.option_c },
          { value: "option_d", text: @question.option_d }
        ]
      } %>
  <%= render "govuk_publishing_components/components/button", { text: "Submit Answer" } %>
<% end %>

app/views/take_quiz/results.html.erb
<% content_for :page_title, "Quiz Results" %>
<% content_for :back_link, quiz_path(@quiz) %>

<p class="govuk-body">Congratulations, you've completed the quiz: <%= @quiz.title %></p>

<p class="govuk-body">You scored <%= @score %> out of <%= @quiz.questions.count %>.</p>

<% if (name = current_user&.username || @guest_username).present? %>
  <p class="govuk-body">
    <%= current_user.present? ? "User: #{name}" : "Guest: #{name}" %>
  </p>
<% end %>

<div class="govuk-button-group">
  <%= render "govuk_publishing_components/components/button", { text: "Back to Dashboard", href: quizzes_path(@quiz) } %>
</div>